name: git fetch upstream merge upstream push action
description: git fetch upstream merge upstream push action
author: RekGRpth
runs:
  using: composite
  steps:
    - run: "${GITHUB_ACTION_PATH}/action.sh"
      shell: sh
