name: git fetch upstream action
description: git fetch upstream action
author: RekGRpth
inputs:
  branch:
    description: git fetch branch
  repository:
    description: git fetch repository
    required: true
  url:
    description: git fetch url
    default: https://github.com/
runs:
  using: composite
  steps:
    - run: |
        set -eux
        INPUTS_BRANCH="${{ inputs.branch }}"
        git remote add --fetch --track "${INPUTS_BRANCH:-${GITHUB_REF##*/}}" upstream "${{ inputs.url }}${{ inputs.repository }}.git"
      shell: sh
