name: git fetch upstream merge push shell action 
description: git fetch upstream merge push shell action 
author: RekGRpth
runs:
  using: composite
  steps:
    - run: "${GITHUB_ACTION_PATH}/action.sh"
      shell: sh
